# Generated by Django 4.1.2 on 2025-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_plugin', '0007_add_index_data_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
