# Generated by Django 4.1.2 on 2025-05-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_plugin', '0008_uploaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='upload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_plugin.upload'),
        ),
    ]
